#!/bin/bash
shopt -s expand_aliases

unalias alohomora
unalias aparecium
unalias apparate
unalias avada-kedavra
unalias diminuendo
unalias engorgio
unalias epoximize
unalias finite-incantatum
unalias gemino
unalias homenum-revelio
unalias imperio
unalias legilimens
unalias locomotor
unalias lumos
unalias lumos-solem
unalias obliviate
unalias petrificus-totalis
unalias portus
unalias prior-incantato
unalias reducio
unalias reducto
unalias rennervate
unalias specialis-revelio

echo "don't be such a muggle..."
echo ''
