#!/bin/bash
shopt -s expand_aliases

alias alohomora=chmod
alias aparecium='ls -a'
alias apparate=cd
alias avada-kedavra=pkill
alias diminuendo=zip
alias engorgio=unzip
alias epoximize=cat
alias finite-incantatum='source ./finite-incantatum'
alias gemino=cp
alias homenum-revelio=finger
alias imperio=sudo
alias legilimens=gdb
alias locomotor=mv
alias lumos=ls
alias lumos-solem='ls -l'
alias obliviate=clear
alias petrificus-totalis='pkill -TSTP'
alias portus=ln
alias prior-incantato=history
alias reducio=zip
alias reducto=rm
alias rennervate='pkill -CONT'
alias specialis-revelio=file

echo 'Welcome to potteriSH!'
echo ''
